spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.191.131:3306/guli_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 199693

mybatis-plus:
  mapper-locations: classpath:/mapper/sms/*.xml

server:
  port: 11000